export default {
  COUCHDB_USER: "couchusername",
  COUCHDB_PASS: "couchpassword",
  COUCHDB_SECRET: "couchsecret",
  SESSION_SECRET: "somesecret",
  PRIVATE_KEY: {
    "p": "_1FP2ALnwAOeQ28OBS2LYmaOs0yP1zNy_eK6UuEdB9L8vKIWB0bi-O2-QaZT1iqhn1Yq_XFlN8ObpSfEJtmNzOVqgS96itXKugQ3eJLqAYfxNkDcMomKb2iP4cu9BaUrSIBfdDU4XhlJNiMXELOOfRKRaeyufFFHX2JSzOqrdOc",
    "kty": "RSA",
    "q": "tjUOuPR7q0wu1e1EdKOVffngyKDJkMbibfFzlsKtuNjxo_Xkth1YCw3Y5ElLHRDoOgbOvbdkEtMq5QipweV_Vo1_6CKbR0xoHg52uZJTMoteUvzd0wKv3qvOvxWHeKLzSGpmPq0P4dRanT7Cw9LVH5sihLtLnI2eaRH2gYv_vtM",
    "d": "TIQCaAK1pA8JUbKwheK5xnkIAYtbsZO5T8yfLntzoFtWFGYcjWZa9u-CEKnn4BjFGVGzAA2ry6NZoI-zUdY6gxAvzABhQGOL7joghzI4ypnAE8RYXj0yw9bVHArGse_QowW2RXWp4RA-dVtFheg6KyB9Mo1-Ju3JrjbCQAgbFkfOn5gi-FIREs5pUlUrjauABbI1db0oLPgvPGOjhN-tOOjO88yD5HbfpCFId6dLi5To1x4XXv_3mD7HfW6mOMBimExAN8E3I341wB-tkFTDGzM-2d_6Nqy9ndfyfu4XcA3l77gQa4gf2JFWnyR9VHsP_6pfxUFo887egmpM5Pn0ZQ",
    "e": "AQAB",
    "use": "enc",
    "kid": "W_Rhc4U7rGQye3y4iy43l3BntE67HjVh1VPq-UyyiXE",
    "qi": "mXUiXomYr_tPAZyhGGgZVKbKR7-8iFNGfjuxLUr0V6MdwrvPglFSvQKBEBjemnGDH5Y_cTtEjX0EtlRK8cPgExWS4bKXJt1fGCrSubZwcyueYx0KeDBoA3sifO6H6HbxHx4uRgK5fhLRV2jc5Bb0XezZBtxc8mYWtJpZF_dvE-U",
    "dp": "PhdGNaAvQBEhMgEWBchXt2x9k7kw2gMXGgtDiNhaOQbkk_NPLCHfHO6kcE7E4Lapa5iHB-_Fz9PwTC_pkhEiXQwF5LjpMk5f6PERlG8WHZ0z2h_X7Spp0kI5i44CwBa0-gLOM_KlbKz1kwbhmxwvsNcNKhd3L6CMnPPKcy82100",
    "alg": "RSA-OAEP-256",
    "dq": "KQCvm3eJDPdL4uBN82GMlpjQuNVWBrp64frf5CFTLrHDTv5axZC861_mWxkTSisv1z8I7zCB2KqkkH3ula-rhDK7geWnw9ex5nGizgfbqRgr1ckJsh58rUNEd0PFBKTG0pj_AUO4uz0qVxB0i9S6GS60CeKMFWLZLxPXwTdcCfk",
    "n": "tbi5SAJtZuqhEyg8kN0DXDGGeeA6dDxm3AOEDOall-umdJ08dDZw6eDuYm3dHkun9jE6GY4h1hQRlqTHGX-XJPA6THaI_fBJo5nnZBjTQ7MZf4RR2PVLWTatrKKrpoS0Qr4GPrsTIHFl7FSFozCtZobV5rLZcHJMf5576VlIinJu_GiEOVR1fyo7hC5QGLhIw4j11haQdGxDYICzPBX0BoWSwqFfBncc_AQ28xQ7eyVmsv3ayR2DjU6hrjySFXj8wFvm-m4zxZIQ3GBqDIvutewFkFsNq9WPG5eoVmoKd-1XjbbY9mGgPVv6DawLBv26CbAt2RKeSS7aGhC6iy3MZQ"
},
  SENDGRID_API_KEY: "SG.somekeyvalue",
  MAILERLITE_API_KEY: "123123123123123",
  SUPPORT_EMAIL: "support@somedomain.com",
  SUPPORT_URGENT_EMAIL: "urgent@somedomain.com",
  URGENT_MESSAGE_SUBJECT: "Urgent message received",
  URGENT_MESSAGE_BODY: "Hi,<br><br>This auto-reply is to confirm that we got your urgent message.<br>Your message will appear as a notification and a text message on the developer's phone, which they'll see right away (if they're awake).<br><br>If you have anything else to add that might help us resolve your issue, just reply to this.<br>Is your problem related to one of your documents, or all of them?<br>Does it occur on one of your devices, or all of them?<br>Do you grant us permission to access your account?<br>Anything you can think of, please let us know.<br><br>We're sorry you're having trouble... we'll do our best to help!<br>The Gingko Team",
  NTFY_URL: "https://ntfy.sh/my_topic",
  STRIPE_SECRET_KEY: "sk_test_123412341234",
  URL_ROOT: "https://app.example.com",
};
